name: Train on Pull Request
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Train
        run: az ml job create --file ./src/job.yml --workspace-name 'mlw-dp100-labs2' --resource-group 'rg-dp100-labs'
